/* Local Leaflet distribution; the image and parking polygons share CRS.Simple coordinates. */
const detail=document.querySelector('#detail'),layers=new Map();
let spots=[],selected=null,ready=false,interaction=false,resizePending=false;
const bounds=L.latLngBounds([[-983,110],[-108,1385]]);
const map=L.map('mapview',{crs:L.CRS.Simple,zoomControl:false,attributionControl:false,zoomSnap:0,zoomDelta:.5,minZoom:-5,maxZoom:3,scrollWheelZoom:true,touchZoom:true,bounceAtZoomLimits:false,maxBoundsViscosity:1,inertia:false,zoomAnimation:true,fadeAnimation:false,markerZoomAnimation:false,trackResize:false,keyboard:true});
L.imageOverlay('plan-hd.webp',[[-1086,0],[0,1536]],{interactive:false,className:'parking-plan'}).addTo(map);
function fitZoom(){return map.getBoundsZoom(bounds,false,L.point(24,24))}
function movementBounds(){const size=map.getSize(),zoom=map.getZoom(),scale=map.options.crs.scale(zoom);const marginX=Math.max(20,(size.x/scale-bounds.getEast()+bounds.getWest())/2+20),marginY=Math.max(20,(size.y/scale-bounds.getNorth()+bounds.getSouth())/2+20);return L.latLngBounds([bounds.getSouth()-marginY,bounds.getWest()-marginX],[bounds.getNorth()+marginY,bounds.getEast()+marginX])}
function sync(){if(!ready)return;map.setMaxBounds(movementBounds());const z=map.getZoom(),min=map.getMinZoom();document.querySelector('#zoom').value=Math.round(100*2**(z-min))+'%';document.querySelector('#minus').disabled=z<=min+.001;document.querySelector('#plus').disabled=z>=map.getMaxZoom()-.001}
function reset(){map.stop();map.setView(bounds.getCenter(),fitZoom(),{animate:false});sync()}
function resize(){if(interaction){resizePending=true;return}const old=ready?map.getZoom()-map.getMinZoom():0,center=ready?map.getCenter():bounds.getCenter();map.invalidateSize({pan:false,animate:false});const min=fitZoom();map.setMinZoom(min);map.setMaxZoom(min+Math.log2(12));map.setView(center,Math.max(min,Math.min(min+Math.log2(12),min+old)),{animate:false});ready=true;sync();resizePending=false}
map.on('movestart zoomstart',()=>{interaction=true});map.on('moveend zoomend',()=>{interaction=false;sync();if(resizePending)requestAnimationFrame(resize)});
let rw=0,rh=0,resizeFrame;new ResizeObserver(entries=>{const r=entries[0].contentRect;if(Math.abs(r.width-rw)<1&&Math.abs(r.height-rh)<1)return;rw=r.width;rh=r.height;cancelAnimationFrame(resizeFrame);resizeFrame=requestAnimationFrame(resize)}).observe(document.querySelector('#mapview'));
document.querySelector('#plus').onclick=()=>map.zoomIn(.5);document.querySelector('#minus').onclick=()=>map.zoomOut(.5);document.querySelector('#fit').onclick=reset;
function focusSpot(s){map.stop();map.setView([-s.y,s.x],Math.max(map.getZoom(),map.getMinZoom()+2),{animate:false})}
function normalStyle(s){return{color:'#ffffff',weight:.5,fillColor:s.sold?'#85949c':'#22a578',fillOpacity:.88,opacity:1}}
function empty(){if(selected){const s=spots.find(x=>x.id===selected);layers.get(selected)?.setStyle(normalStyle(s))}selected=null;detail.classList.remove('chosen');document.querySelector('.mapcaption').innerHTML='<span class="level">B3</span><span>负三层<small>点击车位查看模拟报价</small></span>';detail.innerHTML='<div class="empty-symbol">P</div><h3>从一个车位开始</h3><p>点击地图上的车位<br>这里会显示销售状态和价格</p><button class="primary" id="first">看看一个未售车位 <span>↗</span></button>';document.querySelector('#first').onclick=first}
function select(id){const s=spots.find(x=>x.id===id);if(!s)return;if(selected){const old=spots.find(x=>x.id===selected);layers.get(selected)?.setStyle(normalStyle(old))}selected=id;layers.get(id).setStyle({fillColor:'#efad38',color:'#684e15',weight:1.5}).bringToFront();detail.classList.add('chosen');document.querySelector('.mapcaption').innerHTML=`<span class="level">${s.sold?'已售':s.price.toFixed(1)+'万'}</span><span>${s.number}<small>模拟${s.sold?'销售状态':'报价'} · ${s.type}</small></span>`;detail.innerHTML=`<button class="close" aria-label="关闭车位详情">×</button><span class="badge ${s.sold?'gray':''}">${s.sold?'已售':'未售 · 可查看报价'}</span><h3 class="spot-id">${s.number}</h3><p class="subline">负三层 B3 · ${s.type} · 原图编号</p><div class="price-label">${s.sold?'销售状态（模拟）':'车位总价（模拟）'}</div><div class="price">${s.sold?'已售出':s.price.toFixed(1)+'<small>万元</small>'}</div><div class="detailfoot">仅用于交互演示，不代表真实车位报价。</div>`;detail.querySelector('.close').onclick=empty}
function first(){const s=spots.find(x=>!x.sold);if(s){focusSpot(s);select(s.id)}}
document.querySelector('#first').onclick=first;
map.whenReady(()=>{fetch('spots.json?v=hd-numbers-1').then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{spots=data;for(const s of spots){const p=L.polygon(s.points.map(([x,y])=>[-y,x]),{...normalStyle(s),bubblingMouseEvents:false}).addTo(map);p.bindTooltip(s.number,{direction:'top',opacity:1});p.on('click',()=>select(s.id));const el=p.getElement();el.setAttribute('tabindex','0');el.setAttribute('role','button');el.setAttribute('aria-label',`${s.number}，${s.sold?'已售':'未售，模拟价格'+s.price+'万元'}`);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(s.id)}});el.addEventListener('focus',()=>{if(!interaction&&el.matches(':focus-visible'))focusSpot(s)});layers.set(s.id,p)}document.querySelector('#total').textContent=spots.length;document.querySelector('#remaining').textContent=spots.filter(x=>!x.sold).length}).catch(()=>{document.querySelector('#error').hidden=false;document.querySelector('#first').disabled=true});});
document.addEventListener('keydown',e=>{if(e.key==='Escape')empty()});
